### ISSUE TITLE
npm install fails 

### ISSUE THREAD

**Issue by dpolivka-medicomp** [citation-js/plugin-pubmed#3]
npm install of plugin-pubmed fails with latest citation-js installed.  Presumably due to peer dependency in package.json: 
"@citation-js/core": ">=0.5.1 <=0.6"

**Comment by dpolivka-medicomp** [comment]
nm, I'm an idiot

**Comment by larsgw** [comment]
No problem! If that's the case I should probably update that peer dependency anyway.
